### ISSUE TITLE
Add option to choose graph-net-web.json location

### ISSUE THREAD

**Issue by xplosionmind** [manunamz/jekyll-wikilinks#11]
As mentioned by @manunamz in [this issue](https://github.com/manunamz/jekyll-wikilinks/issues/10#issuecomment-857034895), as of right now, while the plugin is installed, it requires an `/assets` folder in which to print the graph data json file.

The plugin user should be given the possibility, instead, to choose a custom directory where to parse `graph-net-web.json`, or, otherwise, its rendering should not be blocked if the folder is missing but the plugin should create it automatically.

Furthermore, a nice extra feature would be to customize the name of the json file.

**Comment by manunamz** [comment]
Updated in [v0.0.4](https://github.com/manunamz/jekyll-wikilinks/releases/tag/v0.0.4).
