### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by xplosionmind** [manunamz/jekyll-wikilinks#14]
In the README, in the D3 Graph Data section, there is the following paragraph:

> D3 can be tricky, so I've created a gist here of a network graph using d3 version 6. You can see in action here (just click the 🕸 in the top-left to toggle it on).

Both links which are present are broken.

**Comment by manunamz** [comment]
Hmm...Weird -- thought I got that earlier.

Fixed: https://github.com/manunamz/jekyll-wikilinks/commit/db2d25c91b558d49c023186bf0f07c1ba21d7095
