### ISSUE TITLE
Automatically slugify anchor headers

### ISSUE THREAD

**Issue by xplosionmind** [manunamz/jekyll-wikilinks#19]
As of right now, headers are recognized using kramdown properties, hence with the slugified title. Nevertheless, in Obsidian, headers containing a space are recognized if the space is present in the wikilink, and not with a dash in its place.

**Example**:  
`[[Hello World#Anchor heading 1]]` is not recognized, and it has to be modified instead as `[[Hello World#anchor-heading-1]]`

I think adding automatic slugification for anchors directly in the plugin makes no difference if the title is already in the supported format, while it converts anchor headers which do not work with spaces.

**Comment by manunamz** [comment]
Fixed (https://github.com/manunamz/jekyll-wikilinks/commit/782b5bf5e4082b75a05bc979b9b6888365f66cc5) and pushed in v0.0.5.
