### ISSUE TITLE
Anchors support

### ISSUE THREAD

**Issue by xplosionmind** [manunamz/jekyll-wikilinks#2]
- [x] Support the ability to link to anchors inside a file, by using the following syntax: `[[Example note#Example Anchor]]`
- [x] Support this feature in conjunction with note aliases `[[Example note#Example Anchor|This is an example!]]`

**Comment by manunamz** [comment]
Updated in [v0.0.4](https://github.com/manunamz/jekyll-wikilinks/releases/tag/v0.0.4).
