### ISSUE TITLE
Note preview on hover

### ISSUE THREAD

**Issue by xplosionmind** [manunamz/jekyll-wikilinks#22]
I do not know if this could be considerable as a feature for this plugin, yet, it would be great if some guidelines could be given in order to show previews of the content of the note a wikilink refers to.

**Comment by manunamz** [comment]
This is outside of the scope of this gem. But I will be releasing a full template, which includes hover preview. There will be tutorials, how-to's, and I will eventually open up the code.

In the meantime, my hover-preview is basically  the `link-previews` include from [maximevaillancourt's template](https://github.com/maximevaillancourt/digital-garden-jekyll-template) with appropriate changes around [here](https://github.com/maximevaillancourt/digital-garden-jekyll-template/blob/master/_includes/link-previews.html#L72). There is also simply-jekyll's [tooltip](https://github.com/raghuveerdotnet/simply-jekyll/search?q=tooltip) implementation (which has behaved snappier for me).
