### ISSUE TITLE
Latex

### ISSUE THREAD

**Issue by Mara-Li** [manunamz/jekyll-wikilinks#26]
Latex (from jekyll spaceship) are not supported and converted to strike. 
![image](https://user-images.githubusercontent.com/30244939/142594121-1fb21452-8423-4a69-b506-6fa81f738d7b.png)

**Comment by manunamz** [comment]
I am unable to reproduce this -- `jekyll-spaceship` latex/mathjax is working fine with my local install of `jekyll-wikilinks`.

This markdown:
```markdown
$ 1 + 2 = 3 $

$ \frac{A}{B}$
```

Produced this html for me:
<img width="158" alt="Screen Shot 2021-11-24 at 8 47 14 PM" src="https://user-images.githubusercontent.com/75578970/143356846-5af1f8b2-2065-492e-aba2-a673c4bd001c.png">


Can you display the markdown that was used and the rendered output in html?

**Comment by Mara-Li** [comment]
Well, I forgot to add : It was in an embed file!

**Comment by manunamz** [comment]
Same thing -- it works for me just fine:

<img width="749" alt="Screen Shot 2021-11-26 at 12 25 55 PM" src="https://user-images.githubusercontent.com/75578970/143615038-55279f3f-c943-442d-a9d3-f07b7eca3018.png">
